import { createHash } from "node:crypto";
import { TRAIN_SEEDS } from "../evalset";
import { PHYSICS_SHA, type RunRecord } from "./schema";

const ENV = "aether-station@0.1.0-benchmark";
const TRAIN10 = TRAIN_SEEDS.slice(0, 10);

function scenarioHash(seeds: readonly number[]): string {
  return createHash("sha256").update(JSON.stringify(seeds)).digest("hex").slice(0, 16);
}

const TRAIN10_HASH = scenarioHash(TRAIN10);

export const LEDGER: readonly RunRecord[] = [
  {
    run_id: "aether-physics-conservation",
    kind: "physics_audit",
    status: "passed",
    domain: "aether",
    environment_version: ENV,
    agent_version: "none",
    code_sha: PHYSICS_SHA,
    physics_sha: PHYSICS_SHA,
    agent_sha: null,
    scenario_hash: null,
    config_hash: null,
    seed_set: null,
    parent_run_id: null,
    failure_class: null,
    metrics: { physics: "PASS" },
    artifacts: ["outputs/conservation.json", "outputs/reachability.json"],
    reproduction_command: "npm run test:physics -- --full",
    claims: [
      {
        type: "measured",
        statement: "math3d/dynamics/audit match bdfff5b. Open-loop H/E conservation holds.",
        evidence_artifact: "outputs/conservation.json",
      },
    ],
  },
  {
    run_id: "aether-baseline-train10",
    kind: "benchmark_run",
    status: "failed",
    domain: "aether",
    environment_version: ENV,
    agent_version: "baseline",
    code_sha: "f39a9ed67b4b630b3a16e3d03c7dff2b70f0a8ba",
    physics_sha: PHYSICS_SHA,
    agent_sha: "f39a9ed67b4b630b3a16e3d03c7dff2b70f0a8ba",
    scenario_hash: TRAIN10_HASH,
    config_hash: "baseline",
    seed_set: TRAIN10,
    parent_run_id: "aether-physics-conservation",
    failure_class: "online_gate_fail",
    metrics: { allGates: 0, attitude: 0.1, rate: 0.8, fuel: 1, param: 0.3, fdir: 1 },
    artifacts: ["outputs/eval-baseline-train10.json"],
    reproduction_command: "npm run eval -- --controller baseline --set train --count 10",
    claims: [
      {
        type: "measured",
        statement: "Baseline train-10 all-gates 0/10 (att 1/10).",
        evidence_artifact: "outputs/eval-baseline-train10.json",
      },
    ],
  },
  {
    run_id: "aether-v2-train10",
    kind: "benchmark_run",
    status: "failed",
    domain: "aether",
    environment_version: ENV,
    agent_version: "discrete-pulse-v2",
    code_sha: "5a3bb2ba74054fe598b889ee3c0275658d3ed9c1",
    physics_sha: PHYSICS_SHA,
    agent_sha: "5a3bb2ba74054fe598b889ee3c0275658d3ed9c1",
    scenario_hash: TRAIN10_HASH,
    config_hash: "discrete-pulse-v2/beam28",
    seed_set: TRAIN10,
    parent_run_id: "aether-baseline-train10",
    failure_class: "online_gate_fail",
    metrics: { allGates: 0, attitude: 0, rate: 0.1, fuel: 0.9, param: 0.2, fdir: 1 },
    artifacts: ["outputs/eval-v2-train10.json"],
    reproduction_command: "npm run eval -- --controller discrete-pulse-v2 --set train --count 10",
    claims: [
      {
        type: "measured",
        statement: "discrete-pulse-v2 train-10 all-gates 0/10.",
        evidence_artifact: "outputs/eval-v2-train10.json",
      },
    ],
  },
  {
    run_id: "aether-knn-value-train10",
    kind: "benchmark_run",
    status: "stopped",
    domain: "aether",
    environment_version: ENV,
    agent_version: "discrete-pulse-v2-knn",
    code_sha: "c0d80f81bab63d1195d18cd5632cf6c4daf1c9d1",
    physics_sha: PHYSICS_SHA,
    agent_sha: "archive/control-v2-final",
    scenario_hash: TRAIN10_HASH,
    config_hash: "knn-value",
    seed_set: TRAIN10,
    parent_run_id: "aether-v2-train10",
    failure_class: "ood_value_heuristic",
    metrics: { allGates: 0, attitude: 0, rate: 0.3, fuel: 1, param: 0.2, fdir: 1 },
    artifacts: ["outputs/eval-v2-knn-train10.json", "outputs/eval-ablation-train10.json"],
    reproduction_command: "npm run eval:ablation-train10",
    claims: [
      {
        type: "measured",
        statement: "kNN-value train-10 all-gates 0/10. Line STOPPED.",
        evidence_artifact: "outputs/eval-v2-knn-train10.json",
      },
      {
        type: "deprecated",
        statement: "Do not resume kNN-value as a capture planner.",
        evidence_artifact: "docs/control-v2-findings.md",
      },
    ],
  },
  {
    run_id: "aether-belief-audit-train10",
    kind: "research_study",
    status: "archived",
    domain: "aether",
    environment_version: ENV,
    agent_version: "discrete-pulse-v2",
    code_sha: "99f0901bad7b3d7da0ecb4d8a14ba5c0c14521dc",
    physics_sha: PHYSICS_SHA,
    agent_sha: "archive/action-macro-belief-audit",
    scenario_hash: TRAIN10_HASH,
    config_hash: null,
    seed_set: TRAIN10,
    parent_run_id: "aether-knn-value-train10",
    failure_class: null,
    metrics: { wiredToController: false },
    artifacts: ["outputs/belief-truth-audit-train10.json"],
    reproduction_command: "npm run eval:belief-audit",
    claims: [
      {
        type: "measured",
        statement: "Estimator q/ω error is not the attitude-gate failure.",
        evidence_artifact: "outputs/belief-truth-audit-train10.json",
      },
    ],
  },
  {
    run_id: "aether-action-macros",
    kind: "research_study",
    status: "archived",
    domain: "aether",
    environment_version: ENV,
    agent_version: "offline-macros",
    code_sha: "99f0901bad7b3d7da0ecb4d8a14ba5c0c14521dc",
    physics_sha: PHYSICS_SHA,
    agent_sha: "archive/action-macro-belief-audit",
    scenario_hash: null,
    config_hash: "2-4-segment",
    seed_set: null,
    parent_run_id: "aether-belief-audit-train10",
    failure_class: "perp_leak",
    metrics: { readyToWire: false },
    artifacts: ["outputs/action-macro-library.json"],
    reproduction_command: "npm run eval:action-macros",
    claims: [
      {
        type: "search_unreached",
        statement: "2–4 pulse macros: 0/1960 reduce ω_∥ without growing ω_⊥. Not a plant-impossibility proof.",
        evidence_artifact: "outputs/action-macro-library.json",
      },
    ],
  },
  {
    run_id: "aether-wrench-nullspace",
    kind: "research_study",
    status: "archived",
    domain: "aether",
    environment_version: ENV,
    agent_version: "offline-nullspace",
    code_sha: "65d6992a47dba8c0acfa5b941151373ce04729b9",
    physics_sha: PHYSICS_SHA,
    agent_sha: "archive/wrench-nullspace-study",
    scenario_hash: null,
    config_hash: "8-16-seg",
    seed_set: null,
    parent_run_id: "aether-action-macros",
    failure_class: "search_unreached_under_budget",
    metrics: { readyToWire: false, rhoMedian: 2.83 },
    artifacts: ["outputs/wrench-nullspace-study.json"],
    reproduction_command: "npm run eval:wrench-nullspace",
    claims: [
      {
        type: "measured",
        statement: "Wrench remains rank-3 after one jet fail. Short-pulse ρ median 2.83.",
        evidence_artifact: "outputs/wrench-nullspace-study.json",
      },
      {
        type: "search_unreached",
        statement: "16-segment cancel is terminal-only under budget. Not proven unreachable.",
        evidence_artifact: "outputs/wrench-nullspace-study.json",
      },
    ],
  },
  {
    run_id: "aether-robust-terminal",
    kind: "research_study",
    status: "archived",
    domain: "aether",
    environment_version: ENV,
    agent_version: "offline-robust-terminal",
    code_sha: "7910694e4422e590eac5b9e19b635f06ed56013b",
    physics_sha: PHYSICS_SHA,
    agent_sha: "archive/robust-terminal-study",
    scenario_hash: null,
    config_hash: "eta-2sigma",
    seed_set: null,
    parent_run_id: "aether-wrench-nullspace",
    failure_class: "online_gate_fail",
    metrics: { nominalCapture: 6 / 42, readyToWire: false },
    artifacts: ["outputs/robust-terminal-study.json"],
    reproduction_command: "npm run eval:robust-terminal",
    claims: [
      {
        type: "measured",
        statement: "Robust terminal cancellation nominal capture 6/42 (14%), near-close only.",
        evidence_artifact: "outputs/robust-terminal-study.json",
      },
      {
        type: "search_unreached",
        statement: "Did not meet 80%/70% capture gates under 24 segments. READY TO WIRE: NO.",
        evidence_artifact: "outputs/robust-terminal-study.json",
      },
    ],
  },
  {
    run_id: "aether-benchmark-v0.1.0",
    kind: "benchmark_release",
    status: "passed",
    domain: "aether",
    environment_version: ENV,
    agent_version: "baseline",
    code_sha: "v0.1.0-benchmark",
    physics_sha: PHYSICS_SHA,
    agent_sha: "baseline",
    scenario_hash: TRAIN10_HASH,
    config_hash: "release",
    seed_set: TRAIN_SEEDS.slice(0, 2),
    parent_run_id: "aether-physics-conservation",
    failure_class: null,
    metrics: { taskSolved: "NO", researchBenchmarkReady: "YES" },
    artifacts: ["outputs/release/release-manifest.json", "docs/release/benchmark-card.md"],
    reproduction_command: "npm run eval -- --controller baseline --set smoke && npm run release:manifest",
    claims: [
      {
        type: "measured",
        statement: "Benchmark v0.1.0 published. Task solved NO. Infrastructure PASS.",
        evidence_artifact: "docs/release/benchmark-card.md",
      },
    ],
  },
];

export function runById(id: string): RunRecord | undefined {
  return LEDGER.find((r) => r.run_id === id);
}
